package org.apache.hadoop.hive.serde2.protobuf;
//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: addressbook.proto

public final class AddressBookProtos {
private AddressBookProtos() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public static final class Person extends
   com.google.protobuf.GeneratedMessage {
 // Use Person.newBuilder() to construct.
 private Person() {
   initFields();
 }
 private Person(boolean noInit) {}
 
 private static final Person defaultInstance;
 public static Person getDefaultInstance() {
   return defaultInstance;
 }
 
 public Person getDefaultInstanceForType() {
   return defaultInstance;
 }
 
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return AddressBookProtos.internal_static_tutorial_Person_descriptor;
 }
 
 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return AddressBookProtos.internal_static_tutorial_Person_fieldAccessorTable;
 }
 
 // required string name = 1;
 public static final int NAME_FIELD_NUMBER = 1;
 private boolean hasName;
 private java.lang.String name_ = "";
 public boolean hasName() { return hasName; }
 public java.lang.String getName() { return name_; }
 
 // required int32 id = 2;
 public static final int ID_FIELD_NUMBER = 2;
 private boolean hasId;
 private int id_ = 0;
 public boolean hasId() { return hasId; }
 public int getId() { return id_; }
 
 // optional string email = 3;
 public static final int EMAIL_FIELD_NUMBER = 3;
 private boolean hasEmail;
 private java.lang.String email_ = "";
 public boolean hasEmail() { return hasEmail; }
 public java.lang.String getEmail() { return email_; }
 
 private void initFields() {
 }
 public final boolean isInitialized() {
   if (!hasName) return false;
   if (!hasId) return false;
   return true;
 }
 
 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (hasName()) {
     output.writeString(1, getName());
   }
   if (hasId()) {
     output.writeInt32(2, getId());
   }
   if (hasEmail()) {
     output.writeString(3, getEmail());
   }
   getUnknownFields().writeTo(output);
 }
 
 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;
 
   size = 0;
   if (hasName()) {
     size += com.google.protobuf.CodedOutputStream
       .computeStringSize(1, getName());
   }
   if (hasId()) {
     size += com.google.protobuf.CodedOutputStream
       .computeInt32Size(2, getId());
   }
   if (hasEmail()) {
     size += com.google.protobuf.CodedOutputStream
       .computeStringSize(3, getEmail());
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }
 
 public static AddressBookProtos.Person parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data).buildParsed();
 }
 public static AddressBookProtos.Person parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data, extensionRegistry)
            .buildParsed();
 }
 public static AddressBookProtos.Person parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data).buildParsed();
 }
 public static AddressBookProtos.Person parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data, extensionRegistry)
            .buildParsed();
 }
 public static AddressBookProtos.Person parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input).buildParsed();
 }
 public static AddressBookProtos.Person parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input, extensionRegistry)
            .buildParsed();
 }
 public static AddressBookProtos.Person parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   Builder builder = newBuilder();
   if (builder.mergeDelimitedFrom(input)) {
     return builder.buildParsed();
   } else {
     return null;
   }
 }
 public static AddressBookProtos.Person parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   Builder builder = newBuilder();
   if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
     return builder.buildParsed();
   } else {
     return null;
   }
 }
 public static AddressBookProtos.Person parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input).buildParsed();
 }
 public static AddressBookProtos.Person parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input, extensionRegistry)
            .buildParsed();
 }
 
 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(AddressBookProtos.Person prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }
 
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder> {
   private AddressBookProtos.Person result;
   
   // Construct using AddressBookProtos.Person.newBuilder()
   private Builder() {}
   
   private static Builder create() {
     Builder builder = new Builder();
     builder.result = new AddressBookProtos.Person();
     return builder;
   }
   
   protected AddressBookProtos.Person internalGetResult() {
     return result;
   }
   
   public Builder clear() {
     if (result == null) {
       throw new IllegalStateException(
         "Cannot call clear() after build().");
     }
     result = new AddressBookProtos.Person();
     return this;
   }
   
   public Builder clone() {
     return create().mergeFrom(result);
   }
   
   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return AddressBookProtos.Person.getDescriptor();
   }
   
   public AddressBookProtos.Person getDefaultInstanceForType() {
     return AddressBookProtos.Person.getDefaultInstance();
   }
   
   public boolean isInitialized() {
     return result.isInitialized();
   }
   public AddressBookProtos.Person build() {
     if (result != null && !isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return buildPartial();
   }
   
   private AddressBookProtos.Person buildParsed()
       throws com.google.protobuf.InvalidProtocolBufferException {
     if (!isInitialized()) {
       throw newUninitializedMessageException(
         result).asInvalidProtocolBufferException();
     }
     return buildPartial();
   }
   
   public AddressBookProtos.Person buildPartial() {
     if (result == null) {
       throw new IllegalStateException(
         "build() has already been called on this Builder.");
     }
     AddressBookProtos.Person returnMe = result;
     result = null;
     return returnMe;
   }
   
   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof AddressBookProtos.Person) {
       return mergeFrom((AddressBookProtos.Person)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }
   
   public Builder mergeFrom(AddressBookProtos.Person other) {
     if (other == AddressBookProtos.Person.getDefaultInstance()) return this;
     if (other.hasName()) {
       setName(other.getName());
     }
     if (other.hasId()) {
       setId(other.getId());
     }
     if (other.hasEmail()) {
       setEmail(other.getEmail());
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }
   
   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder(
         this.getUnknownFields());
     while (true) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           this.setUnknownFields(unknownFields.build());
           return this;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             this.setUnknownFields(unknownFields.build());
             return this;
           }
           break;
         }
         case 10: {
           setName(input.readString());
           break;
         }
         case 16: {
           setId(input.readInt32());
           break;
         }
         case 26: {
           setEmail(input.readString());
           break;
         }
       }
     }
   }
   
   
   // required string name = 1;
   public boolean hasName() {
     return result.hasName();
   }
   public java.lang.String getName() {
     return result.getName();
   }
   public Builder setName(java.lang.String value) {
     if (value == null) {
 throw new NullPointerException();
}
result.hasName = true;
     result.name_ = value;
     return this;
   }
   public Builder clearName() {
     result.hasName = false;
     result.name_ = getDefaultInstance().getName();
     return this;
   }
   
   // required int32 id = 2;
   public boolean hasId() {
     return result.hasId();
   }
   public int getId() {
     return result.getId();
   }
   public Builder setId(int value) {
     result.hasId = true;
     result.id_ = value;
     return this;
   }
   public Builder clearId() {
     result.hasId = false;
     result.id_ = 0;
     return this;
   }
   
   // optional string email = 3;
   public boolean hasEmail() {
     return result.hasEmail();
   }
   public java.lang.String getEmail() {
     return result.getEmail();
   }
   public Builder setEmail(java.lang.String value) {
     if (value == null) {
 throw new NullPointerException();
}
result.hasEmail = true;
     result.email_ = value;
     return this;
   }
   public Builder clearEmail() {
     result.hasEmail = false;
     result.email_ = getDefaultInstance().getEmail();
     return this;
   }
   
   // @@protoc_insertion_point(builder_scope:tutorial.Person)
 }
 
 static {
   defaultInstance = new Person(true);
   AddressBookProtos.internalForceInit();
   defaultInstance.initFields();
 }
 
 // @@protoc_insertion_point(class_scope:tutorial.Person)
}

private static com.google.protobuf.Descriptors.Descriptor
 internal_static_tutorial_Person_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_tutorial_Person_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\021addressbook.proto\022\010tutorial\"1\n\006Person\022" +
   "\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005email\030\003 \001(\t" +
   "B)\n\024com.example.tutorialB\021AddressBookPro" +
   "tos"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
   new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
     public com.google.protobuf.ExtensionRegistry assignDescriptors(
         com.google.protobuf.Descriptors.FileDescriptor root) {
       descriptor = root;
       internal_static_tutorial_Person_descriptor =
         getDescriptor().getMessageTypes().get(0);
       internal_static_tutorial_Person_fieldAccessorTable = new
         com.google.protobuf.GeneratedMessage.FieldAccessorTable(
           internal_static_tutorial_Person_descriptor,
           new java.lang.String[] { "Name", "Id", "Email", },
           AddressBookProtos.Person.class,
           AddressBookProtos.Person.Builder.class);
       return null;
     }
   };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

public static void internalForceInit() {}

// @@protoc_insertion_point(outer_class_scope)
}
